### ISSUE TITLE
Image added in Footer is three times to small

### ISSUE THREAD

**Issue by mediaessenz** [bithost-gmbh/pdfviewhelpers#132]
I'm using v2.2 of your extension and just realized that a png image added in a pdf:footer section get a smaller size (1/3) as a image with the same size I added in a pdf:header section.
Event setting the size to 100, 200 or 300% hat no effect.

**Comment by mediaessenz** [comment]
I fixed the problem by change the footer.posY from -10 to -40

**Comment by mediaessenz** [comment]
A really cool extension BTW. I <3 it!

The possibility to change the name of a generated pdf would be a really cool thing.

**Comment by maechler** [comment]
@mediaessenz 

The problem you are describing is most likely due to the option `fitOnPage` being set on your image. Which leads to an automatic rescaling when the image does not fit into the footer space. 
You can deactivate this feature by setting it to false:

```html
<pdf:image src="EXT:pdfviewhelpers/Resources/Public/Example/Bithost.jpg" fitOnPage="0" />
```

or globally for all image ViewHelpers:

```
plugin.tx_pdfviewhelpers.settings.image.fitOnPage = 0
```

You can change the name of the generated PDF file by setting `outputPath` to a different value:

```html
<pdf:document outputPath="your_pdf_name_here.pdf">
        [..]
</pdf:document>
```

If you like the extension, please consider giving it a star on GitHub =)

**Comment by maechler** [comment]
@mediaessenz Could you solve your footer and file name issue?

**Comment by mediaessenz** [comment]
Yes :-)
