### ISSUE TITLE
TCPDF ERROR: Some data has already been output, can't send PDF file

### ISSUE THREAD

**Issue by mightynico** [bithost-gmbh/pdfviewhelpers#164]
After I generate a PDF-File with standard config für tx news I get the output "TCPDF ERROR: Some data has already been output, can't send PDF file".

I try to delete the function on line 7641 in the tcpdf.php file and it works.
```
if (ob_get_contents()) {
					$this->Error('Some data has already been output, can\'t send PDF file');
				}

```
I use the TYPO3 version 8.7.32 width composer
pdfviewhelpers version: 2.3.3
PHP:  7.2.31

**Comment by maechler** [comment]
@mightynico Which version of `news` are you using? Are you using the following link to access the PDF view?

```html
<n:link newsItem="{newsItem}" settings="{settings}" title="{newsItem.title}" configuration="{additionalParams: '&type=28032013'}">
        Download as PDF
</n:link>
```

**Comment by maechler** [comment]
@mightynico Any update on this?

**Comment by maechler** [comment]
Closing because of no response within 2 weeks.

**Comment by mightynico** [comment]
Sorry there was a bereavement in our team, thats why i could'nt test ist. Bit I will this weekend.

**Comment by maechler** [comment]
@mightynico Oh, my condolences! I reopen this issue, although I think it is very likely due to some third party extension or debug statements or just anything that outputs content before the PDF is finished and sent. Just today I successfully tested the news template shipped with `pdfviewhelpers` and the newest version of the `news` extension.
See also https://docs.typo3.org/p/bithost-gmbh/pdfviewhelpers/2.3/en-us/Troubleshooting/Index.html#headers-already-sent

**Comment by mightynico** [comment]
Ok we have fix the problem after restart all systems and resintall the plugins. It was magic. Thanks for your help.

**Comment by maechler** [comment]
I'm glad you could fix the issue!
