### ISSUE TITLE
Remove TCPDF and FPDI source files from the extension

### ISSUE THREAD

**Issue by maechler** [bithost-gmbh/pdfviewhelpers#179]
`TCPDF` and `FPDI` should be required as composer dependencies. For non-composer users we should add installation instructions to the documentation.

See also https://github.com/bithost-gmbh/pdfviewhelpers/issues/178

**Comment by DanielSiepmann** [comment]
This doesn't need to be breaking.
The TER release can still contain the libraries as usual. E.g. check out https://github.com/tomasnorre/typo3-upload-ter#recommendation. The release is uploaded anyway, and can therefore be prepared accordingly. No need to document anything and move the heavy stuff to users.

Everyone who uses TER should probably get the bundled libraries, while everyone using composer should use composer instead.

Would be cool to get that into one of the next releases, so we can use composer patches to alter the libraries, instead of re implementing whole methods to add some small things.

**Comment by maechler** [comment]
@DanielSiepmann Thanks for sharing these resources! You are right, it does not need to be breaking as long as we still include the sources for the TER release. If this could be automated, that would be very handy of course!
I will have a look at this, however I am rather busy at the moment, I do not know when I will get to work on this.

**Comment by DanielSiepmann** [comment]
Thanks for fast response. I didn't publish anything to TER myself, that's why I won't provide a PR. Hope those resources help, and it will make it as none BC in the future. Don't feel pushed by my comments on that topic.
