### ISSUE TITLE
Undefined array key error in ImageViewHelper

### ISSUE THREAD

**Issue by nlehmkuhl** [bithost-gmbh/pdfviewhelpers#231]
TYPO3 11,
PHP 8.2,
pdfviewhelpers 2.5.0

In a StandAloneView when using the ImageViewHelper $processingInstructions['crop'] might not be defined, causing an error:

https://github.com/bithost-gmbh/pdfviewhelpers/blob/cd0390aa5ca103a38e9aeb363c1994e0e260edcd/Classes/ViewHelpers/ImageViewHelper.php#L173

**Comment by maechler** [comment]
@nlehmkuhl Thanks for reporting and providing a fix! 

Unfortunately the tests are failing, it seems that this change could have affected the binary content of the generated PDF file, it could however also be that the tests are failing due to something else.
Anyway the generated PDF files look good to me and you don't need to further look into this, I will take care of the tests.

https://github.com/bithost-gmbh/pdfviewhelpers/actions/runs/6429475685
