### ISSUE TITLE
Error "Imported page does not exist"

### ISSUE THREAD

**Issue by liayn** [bithost-gmbh/pdfviewhelpers#99]
This error occurs using latest version from TER 2.0.1 when using `sourceFile` and `importPage` and when a PDF is created containing multiple pages. This issue is probably related to #41.

One problem is that there is broken code in
https://github.com/bithost-gmbh/pdfviewhelpers/blob/master/Classes/Model/BasePDF.php#L199

`$this->tpl` is never defined. A strict comparison against `0` is always `true`. This leads to calling `$this->useTemplate(NULL);`, subsequently causing the mentioned error.

**Comment by maechler** [comment]
@liayn Thanks for reporting! Maybe `$this->tpl` has been renamed to `$this->templateId` in FPDI v2. But it could also be that more things changed, I will test this as soon as possible.

**Comment by liayn** [comment]
I pushed a very dirty workaround, which fulfills at least our current needs

**Comment by maechler** [comment]
I actually think that it is a good fix for that issue. I had a closer look at FPDI, there is no way to determine the most recently used template anymore, thus we have to keep that information in our own class.

However I changed the implementation to not rely on an additional method, because I think this is less error-prone. I also added functional tests covering that issue.

https://github.com/bithost-gmbh/pdfviewhelpers/blob/e6d1b73d13d3621e4778cee25515147dce888eee/Classes/Model/BasePDF.php#L214-L219

Thanks again for your contribution! If you like the project, please consider giving it a star :) 
I just created a new release `v2.0.2` that includes your fix.
